# Generated by Django 4.2.7 on 2024-02-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobapp.category'),
        ),
    ]
