# Generated by Django 4.2.7 on 2024-02-05 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0007_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.category'),
        ),
    ]
